prompt_file: "~/stylus/datasets/coco_rank.csv"
output_dir: "~/coco_cartoon_output"
skip_generation: False
mask: 'one_hot_loras'
sd_config:
  batch_size: 8
  cfg: 8
  parallel: True
  # 16 replicas of Stable Diffusion running in parallel.
  ports:  [7860, 7861, 7862, 7863, 7864, 7865, 7866, 7867, 7868, 7869, 7870, 7871, 7872, 7873, 7874, 7875]
  checkpoint: 'realistic-vision'
# Note that the description of counterfeit says this.
debias_str: 'best quality, anime style'