prompt_file: "~/stylus/datasets/parti_prompts.csv"
output_dir: "~/parti_diversity"
skip_generation: False
debias_str: 'realistic, best quality'
sd_config:
  cfg: 7
  batch_size_per_mask: 4
  parallel: True
  ports: [7860, 7861, 7862, 7863, 7864, 7865, 7866, 7867, 7868, 7869, 7870, 7871, 7872, 7873, 7874, 7875]
mask: "one_hot_loras"
